service: ${file(config.json):name}

provider:
  name: aws
  runtime: nodejs4.3
  profile: ${file(config.json):provider.profile}
  stage: ${file(config.json):provider.stage}
  region: ${file(config.json):provider.region}

custom:
  webpackIncludeModules: false # enable auto including modules

plugins:
  - serverless-webpack

package:
  exclude:
    - .serverless
    - .webpack
    - coverage
    - .babelrc
    - .eslintignore
    - .eslintrc
    - .gitignore
    - LICENSE
    - package.json
    - README.md
    - serverless.yml
    - webpack.config.js

functions:
  saveUrlAs:
    description: Saves a given URL as an image or document in S3
    memorySize: 1024
    timeout: 30
    handler: lambda.handleRequest
    events:
      - http:
          path: graphql
          method: get
          cors: ${file(config.json):enableCors}
      - http:
          path: graphql
          method: post
          cors: ${file(config.json):enableCors}

resources:
  Resources:
    outputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):outputBucket}
